import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "./components/Header";
import HeaderSpacer from "./components/HeaderSpacer";
import Footer from "./components/Footer";

export const metadata = {
  title: "ESC-журнал",
  description: "ESC- медиа о жизни студентов",
};

// Подключаем локальные шрифты
import {
  YffraHyper,
  YffraGiga,
  YffraEcto,
  LatoBold,
  LatoItalic,
} from "../../public/fonts/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${YffraHyper.variable}
          ${YffraGiga.variable}
          ${YffraEcto.variable}
          ${LatoBold.variable}
          ${LatoItalic.variable}
          antialiased bg-black
          font-lato
        `}
      >
        <Header />
        <HeaderSpacer />
        {children}
        <Footer/>
      </body>
    </html>
  );
}


// import { Geist, Geist_Mono } from "next/font/google"; было до подключения шрифтов 
// import "./globals.css";

// import Header from "./components/Header";
// import HeaderSpacer from "./components/HeaderSpacer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className="h-full">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
//       >
//         <Header />
//         <HeaderSpacer />
//         {children}
//       </body>
//     </html>
//   );
// }